= HowTo: Test an IDP

== Prepare a custom test configuration
You need to prepare the test target configuration and add the test driver's
metadata (usually comprising multiple entities) to the test target's entity feed.
Lets get started with configuring a series of tests for a single IDP:

=== Copy and modify the template configuration:

- Copy the template configuration project:
  https://github.com/identinetics/s2t2.conf

    # assume your repo is named samltest_idpExampleOrg, your git id is jo123
    CONF_REPO='samltest_idpExampleOrg'
    mkdir $CONF_REPO && cd $CONF_REPO
    git clone https://github.com/identinetics/s2t2.conf .
    rm -rf .git && git init  # replace the original repo with a new one

- Adapt the test configuration:

    There are, by default, 4 config files arranged in following (class) hierarchy:
     1. config_abstr.py   (importing default config from source code repo)
     2. config_driver.py  (test driver - no need to change unless extending test cases)
     3. config_profile.py (test flows and saml profile)
     4. config.py         (test target config & interaction)

- Generate the json-formatted configuration:

    ./make_json.sh.sh  # you need to have docker for linux/osx/windows installed
    git add --all && git commit -m 'my modification'

- Your repo will now contain 2 files:

    generated/config.json  # your consolidated test target configuration
    generated/metdata.xml  # your test drivers metadata to be used by the test target

- Save your configuration on github

    git remote add origin https://github.com/jo123/$CONF_REPO
    git push origin master

- Note: You may use the fork and clone workflow, but you are limited to one fork
   per github repo. If you will be testing multiple test targets you will need more
   than one repo.

== Upload the test driver's metadata to the test target

This may be done either directly at the test target, or by adding it to a metadata feed.

== Executing tests from a browser

- Tests may be fully automated (the interaction definition in the config will handle all IDP requests).
- Tests may be invoked from the web browser or via a simple REST call. When using the REST call the
  test must be fully automated.
- Users need to override the default config with their own configuration stored on github.
  Loading such a config is done by a URL parameter:

    https://webui.samltest.fed-lab.org/swconf?github=<GITHUB-USER/GITHUB-REPO-NAME>&email=<USER-EMAIL>

Example:

    https://webui.samltest.fed-lab.org/swconf?github=myuser/saml2test2-github-config-repo&email=me@example.org


== Executing tests from the command line or a program
To invoke a test you tell the server that you accept a JSON content type. You will receive a dict.
In the standard case you will just assert that the output contains "status": "OK", such as:

    h='https://webui.samltest.fed-lab.org'
    t='IDP-AuthnRedirect-nid_unspecified'
    curl -sH "Accept: application/json" $h/$t | grep '^{"status": "OK"'; echo $?

An example how to run a series of tests from the command line is provided at:
https://github.com/identinetics/docker-saml2test2/blob/master/install/scripts/rest_test.sh

== Automating the browser interaction
The test tool can be configured with match/control commands to automatically proceed when a user
interaction is requested, such as for login or consent.

The configuration (in config.py) is done with:

CONTENT_HANDLER_TRIGGER: list of test cases that apply to a specific set of interactions

CONTENT_HANDLER_INTERACTION: a set of interactions. "matches" has page properties such as the
URL and HTML elements that must match for this rule to trigger. "control" is there to set data
to be submitted to the server.

Calling the test case using curl has the advantage, that pages that do not patch are written out in
source.

== Restricting Users

Users ability to switch to another config by creating a yaml file, holding lines of the form

   <GITHUB-USERNAME>: <USER-EMAIL>

and defining the file in the config using:

   def config(self):
      ...
      self.ACCESS_CONTROL_FILE = '<FILENAME>'

